### ISSUE TITLE
update default example

### ISSUE THREAD

**Issue by agauniyal** [monkberry/monkberrify#1]
From gulp-browserify page -

> #### NOTE: THIS PLUGIN IS NO LONGER MAINTAINED , checkout the recipes by gulp team for reference on using browserify with gulp.

I've read somewhere that it is blacklisted from original browserify as well.

**Comment by agauniyal** [comment]
would this be fine?

```
var gulp = require('gulp');
var browserify = require('browserify');
var babelify = require('babelify');
var monkberrify = require('monkberrify');
var source = require('vinyl-source-stream');

gulp.task('default', function() {
  return browserify({ entries: './app.js' })
    .transform("babelify", {presets: ["es2015"]})
    .transform(monkberrify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('dist'));
});
```

I'm asking because I don't have prior experience with such frontend tooling.

**Comment by antonmedv** [comment]
That's nice.
